from node:18-bullseye

run npm install -g npm
RUN git clone https://github.com/orby-tech/orby-tech-group-telegram-bot.git


RUN cd orby-tech-group-telegram-bot && npm install

CMD cd orby-tech-group-telegram-bot && npx ts-node run.ts     