version: "3"

services:
  orby-tech-group-telegram-bot_deploy:
    build: ./container
    container_name: orby-tech-group-telegram-bot_deploy
    volumes:
      - ./value:/orby-tech-group-telegram-bot/value

    env_file:
      - .env
